26F-Studio/Techmino

parts/language/lang_en.lua

Fixes a capitalization error when calling the color module

---

README.md

- The formatted text replaced with a # heading
- removed other useless font tags
- Added https to the link so that it's clickable

Make the readme Github/Gitee-compatible

---

.github/workflows/build.yml
.github/workflows/updateOSXVersion.py

基于一个模板`Techmino.app.zip`，修改版本号、打包并替换`Techmino.love`资源。
我还不知道这个模板该上传到哪，所以链接还没写，商量一下？

[no ci] 整OS X

---

.github/workflows/build.yml
.github/workflows/updateConfVersion.py
.github/workflows/updateOSXVersion.py

**添加#176 需求的在自动打包的时候添加提交hash**
==================================
这个pr应该不会出bug了~~吧~~
~~求求Z酱看一遍再合并（~~

在自动打包的时候添加提交hash #176

---

parts/language/lang_en.lua
parts/language/lang_zh.lua
parts/list.lua
parts/scenes/mode.lua

显示即将解锁的关卡， closes #194

---

.github/workflows/updateConfVersion.py

修改updateConfVersion.py > 在ci运行的时候修改游戏存档目录

---

Zframework/init.lua

(Experimental) Support controller axises, closes #466

---

parts/bot/bot_cc.lua
parts/bot/init.lua

this should be used with branch 26F-Studio/cold_clear_ai_love2d_wrapper@21be884c781417d59def28edbbdda5e1d2fb2c77, but the change is backward-compatible so we can merge this first.

cc techmino-alize

---

.github/actions/get-cc/action.yml
parts/bot/bot_cc.lua
parts/player/player.lua

This pr enables cc to use
- b2b gauge, attack and extra block system
- variable spawn position 
Notice that this is not backward compatible.
The merge plan should be carefully designed.
Related: 26F-Studio/cold_clear_ai_love2d_wrapper#20

cc techmino-alize 2

---

.github/actions/automatic-test/action.yml

currently only using `parts/fonts/proportional.otf`

check font in automatic test

---

readme.md

renamed AUR version to AUR techmino-client
renamed AUR techmino-client's label from 'AUR' to 'techmino-client'

add AUR(techmino-git) badge

---

parts/bot/bot_cc.lua
parts/modes/drought_l.lua
parts/player/gameEnv0.lua
parts/player/init.lua
parts/player/player.lua
parts/player/seqGenerators.lua

Need to fix: small blocks in replays are gone.

revise sequence generator

---

parts/language/dict_vi.lua
parts/language/dict_zh.lua
parts/language/lang_vi.lua
parts/language/manual_vi.txt

Extend #915 for some minor changes

Update Vietnamese translation (again)

---

parts/scenes/app_arithmetic.lua

Change drawing's icon from D to pencil
Automatically erase the input and play finesseError_long SFX when the input's length = answer's length (allowing user to retype the answer over without hitting Backspace key or waiting to the input is gone)

Update Arithmetric app

---

parts/player/draw.lua
parts/player/init.lua
parts/player/player.lua
parts/player/seqGenerators.lua

new bagline system

---

parts/bot/bot_cc.lua
parts/player/draw.lua
parts/player/player.lua
version.lua

add hold i_s

---

parts/language/lang_vi.lua
parts/language/manual_vi.txt

Welp, update again lol
I haven't updated Zictionary translation yet, so...

Update Vietnamese translation

---

parts/scenes/app_piano.lua

Attemping to fix some bugs in Piano applet

---

parts/data.lua
parts/gameFuncs.lua
parts/gameTables.lua
parts/player/init.lua
parts/scenes/customGame.lua
parts/scenes/mod.lua
parts/scenes/mode.lua
parts/scenes/pause.lua
parts/scenes/replays.lua

refactor GAME.mod

---

parts/language/lang_en.lua
parts/language/lang_es.lua
parts/language/lang_fr.lua
parts/language/lang_id.lua
parts/language/lang_ja.lua
parts/language/lang_pt.lua
parts/language/lang_symbol.lua
parts/language/lang_vi.lua
parts/language/lang_zh.lua
parts/language/lang_zh_code.lua
parts/language/lang_zh_trad.lua
parts/scenes/customGame.lua

make an error with filled lines when using cc

---

parts/scenes/pause.lua

Fix #197 (opened 2 years ago, now will be added)

Add touch gesture for radar

---

parts/player/player.lua

make the bot know the current situation

update field after loading AI

---

parts/data.lua
parts/language/lang_en.lua
parts/language/lang_zh.lua
parts/scenes/customGame.lua
parts/scenes/custom_field.lua

probably fixes (don't auto close issue) #1038

Add checks and error messages for some invalid custom mode data

---

parts/language/lang_en.lua
parts/language/lang_es.lua
parts/language/lang_fr.lua
parts/language/lang_id.lua
parts/language/lang_ja.lua
parts/language/lang_pt.lua
parts/language/lang_symbol.lua
parts/language/lang_vi.lua

"discarded" instead of "abandoned" for 126+ line custom field

Changed a wording in new string

---

parts/player/init.lua
parts/player/player.lua
version.lua

add hold i_s from next

---

parts/modes/dig_quad_10l.lua

fix text in dig quad 10l

---

.github/workflows/main.yml
main.lua

Previously automatic test was somehow not executed.
This pull request brings back the old good automatic test.

Fix auto test

---

parts/net.lua
parts/scenes/net_game.lua

* Altering the behavior of the callback of Websocket when receiving messages: wrapping the text before adding colors and push to the text box
* Bring emoji back
* Expand chat area to almost full screen

Fix multiplayer chat

---

Zframework/widget.lua
parts/language/lang_en.lua
parts/language/lang_vi.lua
parts/scenes/setting_video.lua

Partially fix #811
Use base64 method

Custom image from clipboard

---

parts/modes/custom_clear.lua
parts/modes/custom_puzzle.lua

Fix the issue of AI passing Hold parameters in custom mode
